### ISSUE TITLE
Where's the Rest of Your Script?

### ISSUE THREAD

**Issue by thenorthstar** [gcapozzo/haxballx7#1]
@gcapozzo Hello dude. It seems some stuff on your script is missing. It's not useful so because.

https://github.com/gcapozzo/haxballx7/blob/main/haxbot.js

**Comment by gcapozzo** [comment]
Uploaded the rest of the script, in develop

**Comment by Turtosoo** [comment]
@thenorthstar @saviola777 can you help me?
